# Generated by Django 4.2.5 on 2023-09-28 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='Start_time',
        ),
    ]
