# Generated by Django 4.2.5 on 2023-09-30 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0002_remove_tasks_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='date',
            field=models.DateField(default='2022-10-30'),
            preserve_default=False,
        ),
    ]
